### ISSUE TITLE
add a figure

### ISSUE THREAD

**Issue by bvreede** [NLeSC/reveal-slides#2]
There should be an example slide with a picture.

**Comment by jhidding** [comment]
I could get it to work partially by including an image on a `two-pane` slide and adding

```scss
	&.two-pane {
	  // why not just use "standard blue-pane-right" directly?
	  @include logo-color;
	  @include yellow-flag;
	  @include blue-pane-right;
	  h1, h2, h3, p, ul {
		text-align: left;
		padding-right: 50%;
	  }
	  img {
		position: absolute;
		right: 0;
		top: 0;
	  }
	}
```

to the style. However this only gives the desired layout when reloading the page on the spot, and no when transitioning to the specific slide.
